# Stage 1: build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copy csproj dan restore dependency
COPY *.csproj ./
RUN dotnet restore

# Copy semua source dan build
COPY . .
RUN dotnet publish -c Release -o /app

# Stage 2: runtime image
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "IniGadget.dll"]
